name: .NET

on:
  workflow_dispatch: 
  push:
    branches: [main]
    
      
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Chirp/Chirp.sln
      
    - name: Build
      run: dotnet build Chirp/Chirp.sln --no-restore
     
    - name: Test
      run: dotnet test Chirp/Chirp.sln --no-build --verbosity normal
     
# Det hele minder rigtig meget om gradle. Det sådan i skal tænke det
# hvor man builder, restore og tester sit projekt når man åbner
# gradle var bare lokalt hvor det her er på github via ubuntu
# Det bruges når vi pusher eller puller så kan vi se om koden består vores test
